#!/bin/bash

wallpaper_dir="/usr/share/wallpapers/"

while true; do
  # List files in the wallpaper directory and send them to wofi
  wallpaper=$(find "$wallpaper_dir" -type f -printf '%f\n' |  wofi -dp "Select a wallpaper: " -W 550 -H 300 )

  if [ -n "$wallpaper" ]; then
    config="/home/starrocker/.config/hypr/hyprpaper.conf"
    echo "preload = $wallpaper_dir$wallpaper" > "$config"
    echo "wallpaper = HDMI-A-2, $wallpaper_dir$wallpaper" >>  "$config"
    echo "wallpaper = PHONE, $wallpaper_dir$wallpaper" >>  "$config"
    killall hyprpaper
    hyprpaper & 
    break
  else
    break
  fi
done
